source 'https://github.com/CocoaPods/Specs.git'

target 'MSInputScrollViewController', :exclusive => true do
  pod "MSInputScrollViewController", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "MSInputScrollViewController", :path => "../"

  pod 'FBSnapshotTestCase'
end
